## Login

POST http://3.89.218.253:8000/app/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "kadir_12",
    "password": "123123"
}

### Content
GET http://3.89.218.253:8000/app/content-list/ HTTP/1.1
Content-Type: application/json
Authorization: "Token 2e4f8786ce9ed497e38b0d252cfcb9c5365b7cfddb2c8d988ea1b0ffab3c2710"

# {
#     "name" : "Deneme",
#     "type" : "discussion",
#     "text" : "Lorem ipsum dolor sit amet",
#     "url" : "/content/1/",
#     "learningSpace" : 1
# }
