# Generated by Django 4.1.2 on 2022-12-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
