# Generated by Django 3.2.3 on 2022-11-21 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='votes',
        ),
        migrations.AddField(
            model_name='content',
            name='upVoteCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningspace',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
